name = "hopr"
compatibility_date = "2024-01-01"
main = "workers/index.ts"

[site]
bucket = "./dist"

[env.production]
route = "hopr-432.pages.dev/*"

[env.staging]
route = "staging.hopr.pages.dev/*"

# Variables
[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "hopr-db"
database_id = "2367cac7-781c-4b93-bb93-7743e1a03026"

[[kv_namespaces]]
binding = "CACHE"
id = "973df0713fc746baa0ca71e63da25a4d"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "c75340fc9e934d20bdf8437e4725541b"

[[kv_namespaces]]
binding = "TELEGRAM_STATE"
id = "c75340fc9e934d20bdf8437e4725541b"
