import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, Copy, KeyRound, Plus, Shield, Trash2, Wallet as WalletIcon } from 'lucide-react';
import ThemeToggle from './ThemeToggle';
import { useWallet } from '../context/WalletContext';
import { apiUrl } from '../services/api';

type VaultWallet = { id: string; label: string; source: string; evmAddress: string; solanaAddress: string; isActive: boolean; createdAt: string };

interface WalletsPageProps { onBack: () => void; }
function short(address: string | null) { return address ? `${address.slice(0, 8)}…${address.slice(-6)}` : 'Not available'; }

export default function WalletsPage({ onBack }: WalletsPageProps) {
  const { telegramUser } = useWallet();
  const [wallets, setWallets] = useState<VaultWallet[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [label, setLabel] = useState('');
  const [editingWallet, setEditingWallet] = useState<string | null>(null);
  const [editingLabel, setEditingLabel] = useState('');
  const [importNetwork, setImportNetwork] = useState<'evm' | 'solana'>('evm');
  const [privateKey, setPrivateKey] = useState('');
  const [importConfirmed, setImportConfirmed] = useState(false);
  const [revealWallet, setRevealWallet] = useState<VaultWallet | null>(null);
  const [deleteWallet, setDeleteWallet] = useState<VaultWallet | null>(null);
  const [revealChecks, setRevealChecks] = useState([false, false, false]);
  const [deleteChecks, setDeleteChecks] = useState([false, false]);
  const [confirmation, setConfirmation] = useState('');
  const [revealed, setRevealed] = useState<{ evmPrivateKey: string; solanaPrivateKey: string; warning: string } | null>(null);

  const initData = window.Telegram?.WebApp?.initData;
  const call = async (path: string, body: Record<string, unknown>) => {
    const response = await fetch(apiUrl(path), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ initData, ...body }) });
    const data = await response.json() as { error?: string; wallets?: VaultWallet[]; wallet?: VaultWallet; label?: string; deleted?: boolean; evmPrivateKey?: string; solanaPrivateKey?: string; warning?: string };
    if (!response.ok) throw new Error(data.error ?? 'Wallet request failed.');
    return data;
  };

  const loadWallets = async () => { if (!initData) return; try { const data = await call('/api/telegram/wallets', {}); setWallets(data.wallets ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load wallets.'); } };
  useEffect(() => { void loadWallets(); }, []);

  const createWallet = async () => { setBusy(true); setMessage(''); try { const data = await call('/api/telegram/wallet/create', { ...(label.trim() ? { label: label.trim() } : {}) }); if (data.wallet) setWallets((current) => [data.wallet!, ...current.map((wallet) => ({ ...wallet, isActive: false }))]); setLabel(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create wallet.'); } finally { setBusy(false); } };
  const importWallet = async () => { setBusy(true); setMessage(''); try { const data = await call('/api/telegram/wallet/import', { network: importNetwork, privateKey, label: label || `${importNetwork.toUpperCase()} imported`, confirmRisk: importConfirmed }); if (data.wallet) setWallets((current) => [data.wallet!, ...current.map((wallet) => ({ ...wallet, isActive: false }))]); setPrivateKey(''); setLabel(''); setImportConfirmed(false); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to import wallet.'); } finally { setBusy(false); } };
  const selectWallet = async (wallet: VaultWallet) => { setBusy(true); try { await call('/api/telegram/wallet/active', { walletId: wallet.id }); setWallets((current) => current.map((item) => ({ ...item, isActive: item.id === wallet.id }))); setMessage(`${wallet.label} is now active for trading.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to select wallet.'); } finally { setBusy(false); } };
  const renameWallet = async (wallet: VaultWallet) => { setBusy(true); try { const data = await call('/api/telegram/wallet/rename', { walletId: wallet.id, label: editingLabel }); setWallets((current) => current.map((item) => item.id === wallet.id ? { ...item, label: data.label ?? editingLabel } : item)); setEditingWallet(null); setMessage('Wallet label updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to rename wallet.'); } finally { setBusy(false); } };
  const reveal = async () => { setBusy(true); try { const data = await call('/api/telegram/wallet/reveal', { walletId: revealWallet?.id, confirmation, acknowledgeSecurity: revealChecks[0], acknowledgeClipboard: revealChecks[1], acknowledgeIrreversible: revealChecks[2] }); setRevealed({ evmPrivateKey: data.evmPrivateKey ?? '', solanaPrivateKey: data.solanaPrivateKey ?? '', warning: data.warning ?? '' }); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to reveal keys.'); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await call('/api/telegram/wallet/delete', { walletId: deleteWallet?.id, confirmation, backupConfirmed: deleteChecks[0], acknowledgeIrreversible: deleteChecks[1] }); setWallets((current) => current.filter((wallet) => wallet.id !== deleteWallet?.id)); setDeleteWallet(null); setConfirmation(''); setMessage('Wallet permanently deleted. It cannot be recovered without a backup.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to delete wallet.'); } finally { setBusy(false); } };
  const copy = (value: string) => { void navigator.clipboard.writeText(value); setMessage('Copied. Clear your clipboard after securing the key.'); };

  if (!telegramUser || !initData) return <div className="min-h-screen bg-[#0a0b0f] text-white"><header className="border-b border-gray-800/50"><div className="max-w-4xl mx-auto px-4 h-16 flex items-center justify-between"><button onClick={onBack} className="text-sm text-gray-400 hover:text-white">← Back</button><ThemeToggle /></div></header><main className="max-w-2xl mx-auto px-4 py-16 text-center"><Shield className="mx-auto h-12 w-12 text-brand-300" /><h1 className="mt-4 text-2xl font-bold">Wallet Vault is Telegram-secured</h1><p className="mt-2 text-sm text-gray-400">Open this page from the Hopr Telegram Mini App so your wallet actions can be authenticated securely.</p></main></div>;

  return <div className="min-h-screen bg-[#0a0b0f] text-white"><header className="sticky top-0 z-40 border-b border-gray-800/50 bg-gray-900/85 backdrop-blur-xl"><div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between"><button onClick={onBack} className="flex items-center gap-2 text-sm text-gray-400 hover:text-white"><ArrowLeft className="h-4 w-4" />Back</button><div className="flex items-center gap-3"><h1 className="font-semibold">Wallet Vault</h1><ThemeToggle /></div></div></header><main className="max-w-5xl mx-auto px-4 sm:px-6 py-8 space-y-6"><section className="rounded-2xl border border-brand-400/20 bg-gradient-to-br from-brand-500/15 via-gray-900/70 to-purple-500/10 p-6"><div className="flex gap-4"><div className="rounded-2xl bg-brand-400/15 p-3 h-fit"><Shield className="h-7 w-7 text-brand-200" /></div><div><p className="text-xs uppercase tracking-[0.24em] text-brand-300">Private key custody</p><h2 className="mt-2 text-2xl font-bold">Your wallets, your decision</h2><p className="mt-2 text-sm leading-relaxed text-gray-400">Hopr stores encrypted keys. Choose an active wallet for trading, keep backups offline, and never reveal a private key on a shared or compromised device.</p></div></div></section>
      {message && <div className="rounded-xl border border-brand-400/20 bg-brand-500/10 px-4 py-3 text-sm text-brand-100">{message}</div>}
      <section className="grid gap-4 sm:grid-cols-2">{wallets.map((wallet) => <article key={wallet.id} className={`rounded-2xl border p-5 ${wallet.isActive ? 'border-brand-400/50 bg-brand-500/10' : 'border-gray-800/60 bg-gray-900/60'}`}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><WalletIcon className="h-4 w-4 text-brand-300" /><h3 className="font-semibold">{wallet.label}</h3>{wallet.isActive && <span className="rounded-full bg-green-400/15 px-2 py-0.5 text-[10px] text-green-300">ACTIVE</span>}</div><p className="mt-1 text-xs text-gray-500">{wallet.source === 'imported' ? 'Imported wallet' : 'Generated wallet'}</p></div><button onClick={() => setDeleteWallet(wallet)} className="text-gray-500 hover:text-red-300" aria-label={`Delete ${wallet.label}`}><Trash2 className="h-4 w-4" /></button></div>{editingWallet === wallet.id ? <div className="mt-3 flex gap-2"><input autoFocus value={editingLabel} onChange={(event) => setEditingLabel(event.target.value)} className="min-w-0 flex-1 rounded-lg border border-gray-700 bg-gray-800 px-2 py-1.5 text-xs" /><button onClick={() => void renameWallet(wallet)} disabled={busy || !editingLabel.trim()} className="rounded-lg bg-brand-500/20 px-2 py-1.5 text-xs text-brand-100">Save</button></div> : <button onClick={() => { setEditingWallet(wallet.id); setEditingLabel(wallet.label); }} className="mt-2 text-xs text-brand-300 hover:text-brand-100">Rename wallet</button>}<div className="mt-4 space-y-2 text-xs"><div className="rounded-lg bg-gray-800/50 px-3 py-2"><span className="text-gray-500">EVM</span><div className="mt-1 font-mono text-gray-200">{short(wallet.evmAddress)}</div></div><div className="rounded-lg bg-gray-800/50 px-3 py-2"><span className="text-gray-500">Solana</span><div className="mt-1 font-mono text-gray-200">{short(wallet.solanaAddress)}</div></div></div><div className="mt-4 flex flex-wrap gap-2">{!wallet.isActive && <button onClick={() => void selectWallet(wallet)} disabled={busy} className="rounded-lg bg-brand-500/20 px-3 py-2 text-xs font-semibold text-brand-100">Use for trading</button>}<button onClick={() => { setRevealWallet(wallet); setRevealed(null); setRevealChecks([false, false, false]); setConfirmation(''); }} className="rounded-lg border border-yellow-400/30 px-3 py-2 text-xs text-yellow-200"><KeyRound className="mr-1 inline h-3 w-3" />Reveal keys</button></div></article>)}</section>
      <section className="rounded-2xl border border-gray-800/60 bg-gray-900/60 p-5"><div className="flex items-center gap-2"><Plus className="h-4 w-4 text-brand-300" /><h2 className="font-semibold">Create another wallet</h2></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Wallet label" className="flex-1 rounded-xl border border-gray-700 bg-gray-800/60 px-3 py-2.5 text-sm" /><button onClick={() => void createWallet()} disabled={busy} className="rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white">Generate encrypted wallet</button></div></section>
      <section className="rounded-2xl border border-gray-800/60 bg-gray-900/60 p-5"><div className="flex items-center gap-2"><KeyRound className="h-4 w-4 text-purple-300" /><h2 className="font-semibold">Import a wallet you own</h2></div><p className="mt-2 text-xs text-gray-500">Import only on a private device. The key is encrypted immediately and is never logged.</p><div className="mt-3 grid gap-2 sm:grid-cols-[130px_1fr]"><select value={importNetwork} onChange={(event) => setImportNetwork(event.target.value as 'evm' | 'solana')} className="rounded-xl border border-gray-700 bg-gray-800/60 px-3 py-2.5 text-sm"><option value="evm">EVM private key</option><option value="solana">Solana secret key</option></select><input type="password" value={privateKey} onChange={(event) => setPrivateKey(event.target.value)} placeholder="Paste key only when ready to import" className="rounded-xl border border-gray-700 bg-gray-800/60 px-3 py-2.5 text-sm" /></div><label className="mt-3 flex gap-2 text-xs text-gray-400"><input type="checkbox" checked={importConfirmed} onChange={(event) => setImportConfirmed(event.target.checked)} />I understand I am importing a sensitive secret I control, and I am using a private trusted device.</label><button onClick={() => void importWallet()} disabled={busy || !privateKey || !importConfirmed} className="mt-3 rounded-xl border border-purple-400/30 bg-purple-500/15 px-4 py-2.5 text-sm font-semibold text-purple-100">Import and encrypt</button></section>
      <div className="flex gap-3 rounded-2xl border border-red-500/20 bg-red-500/5 p-4 text-xs leading-relaxed text-red-200/80"><AlertTriangle className="h-4 w-4 shrink-0" />Deleting a wallet is permanent. If you did not back up its private keys, the wallet and all funds controlled by it cannot be recovered.</div>
    </main>
    {revealWallet && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-lg rounded-2xl border border-yellow-500/30 bg-gray-900 p-5"><h2 className="text-lg font-bold text-yellow-100">Reveal private keys — extreme risk</h2><p className="mt-2 text-sm text-gray-400">Anyone who sees these keys can permanently take the wallet. Do not screenshot, email, or paste them into a website.</p>{['I am on a private, trusted device.', 'I understand the keys give full control of the wallet.', 'I have a secure offline backup plan and accept the risk.'].map((text, index) => <label key={text} className="mt-3 flex gap-2 text-xs text-gray-300"><input type="checkbox" checked={revealChecks[index]} onChange={() => setRevealChecks(revealChecks.map((value, itemIndex) => itemIndex === index ? !value : value))} />{text}</label>)}<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder="Type REVEAL PRIVATE KEYS" className="mt-4 w-full rounded-xl border border-gray-700 bg-gray-800 px-3 py-2.5 text-sm" />{revealed ? <div className="mt-4 space-y-3"><p className="text-xs text-red-300">{revealed.warning}</p>{[['EVM private key', revealed.evmPrivateKey], ['Solana secret key', revealed.solanaPrivateKey]].map(([title, value]) => value && <div key={title} className="rounded-xl bg-black/50 p-3"><div className="flex justify-between text-xs text-gray-400"><span>{title}</span><button onClick={() => copy(value)}><Copy className="h-3 w-3" /></button></div><code className="mt-2 block break-all text-xs text-yellow-100">{value}</code></div>)}</div> : <div className="mt-4 flex justify-end gap-2"><button onClick={() => setRevealWallet(null)} className="rounded-lg px-3 py-2 text-sm text-gray-400">Cancel</button><button onClick={() => void reveal()} disabled={busy || !revealChecks.every(Boolean) || confirmation !== 'REVEAL PRIVATE KEYS'} className="rounded-lg bg-yellow-600 px-3 py-2 text-sm font-semibold text-white">Reveal once</button></div>}</div></div>}
    {deleteWallet && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-lg rounded-2xl border border-red-500/30 bg-gray-900 p-5"><h2 className="text-lg font-bold text-red-100">Delete {deleteWallet.label} permanently?</h2><p className="mt-2 text-sm text-gray-400">This cannot be undone. If you did not back up the private keys, you will not be able to recover this wallet or its funds.</p>{['I have backed up the private keys or accept permanent loss.', 'I understand this deletion cannot be reversed.'].map((text, index) => <label key={text} className="mt-3 flex gap-2 text-xs text-gray-300"><input type="checkbox" checked={deleteChecks[index]} onChange={() => setDeleteChecks(deleteChecks.map((value, itemIndex) => itemIndex === index ? !value : value))} />{text}</label>)}<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder="Type DELETE WALLET" className="mt-4 w-full rounded-xl border border-gray-700 bg-gray-800 px-3 py-2.5 text-sm" /><div className="mt-4 flex justify-end gap-2"><button onClick={() => setDeleteWallet(null)} className="rounded-lg px-3 py-2 text-sm text-gray-400">Cancel</button><button onClick={() => void remove()} disabled={busy || !deleteChecks.every(Boolean) || confirmation !== 'DELETE WALLET'} className="rounded-lg bg-red-600 px-3 py-2 text-sm font-semibold text-white">Delete permanently</button></div></div></div>}
  </div>;
}
