"""Generate the Hopr logo set in public/brand/ from one geometry.



The mark is a lowercase "h" whose shoulder is a hop: the arch leaves the stem,

clears the gap and lands as a ball (the next chain). Every file below is

derived from the same paths so the icon, mark, lockups and avatar always match.



    python scripts/build-logo.py

    node scripts/rasterize-logo.mjs   # PNG favicons / avatar from these SVGs

"""

from pathlib import Path



BRAND = Path(__file__).resolve().parent.parent / "public" / "brand"



STROKE = 60

STEM = "M150 110V400"

ARCH = "M150 290C150 212 204 180 260 180C326 180 362 228 366 304"

BALL = (370, 388, 42)

# Bounding box of the mark (stroke caps and ball included).

MARK_BOX = (114, 74, 304, 362)

MARK_CENTER = (266, 255)



GRAD_STOPS = {

    "dark": [("0", "#5b3df5"), (".55", "#8b6bff"), ("1", "#d4c8ff")],

    "light": [("0", "#4325d6"), (".55", "#6646f0"), ("1", "#8f73ff")],

}





def defs(variant: str = "dark", ball_glow: bool = True) -> str:

    stops = "".join(f'<stop offset="{o}" stop-color="{c}"/>' for o, c in GRAD_STOPS[variant])

    ball_stops = (

        '<stop offset="0" stop-color="#f4fffb"/><stop offset=".5" stop-color="#7ff5dc"/><stop offset="1" stop-color="#1fd4ad"/>'

        if variant == "dark"

        else '<stop offset="0" stop-color="#7ff5dc"/><stop offset=".6" stop-color="#1fd4ad"/><stop offset="1" stop-color="#0c9f80"/>'

    )

    cx, cy, _ = BALL

    glow = (

        f'<radialGradient id="hopr-halo" cx="{cx}" cy="{cy}" r="78" gradientUnits="userSpaceOnUse">'

        '<stop offset="0" stop-color="#3ef0c8" stop-opacity=".5"/><stop offset="1" stop-color="#3ef0c8" stop-opacity="0"/></radialGradient>'

        if ball_glow

        else ""

    )

    return (

        "<defs>"

        f'<linearGradient id="hopr-stroke" x1="130" y1="420" x2="360" y2="150" gradientUnits="userSpaceOnUse">{stops}</linearGradient>'

        f'<radialGradient id="hopr-ball" cx="{cx - 12}" cy="{cy - 14}" r="52" gradientUnits="userSpaceOnUse">{ball_stops}</radialGradient>'

        f"{glow}"

        "</defs>"

    )





def mark_paths(ball_glow: bool = True) -> str:

    cx, cy, r = BALL

    halo = f'<circle cx="{cx}" cy="{cy}" r="78" fill="url(#hopr-halo)"/>' if ball_glow else ""

    return (

        f"{halo}"

        f'<g fill="none" stroke="url(#hopr-stroke)" stroke-width="{STROKE}" stroke-linecap="round">'

        f'<path d="{STEM}"/><path d="{ARCH}"/></g>'

        f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="url(#hopr-ball)"/>'

    )





def svg(view_box: str, body: str, width: int, height: int, label: str = "Hopr") -> str:

    return (

        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}" width="{width}" height="{height}" role="img" aria-label="{label}">\n'

        f"  <title>{label}</title>\n"

        "  <!-- An \"h\" whose shoulder hops across and lands as the next chain. Generated by scripts/build-logo.py. -->\n"

        f"  {body}\n"

        "</svg>\n"

    )





def centered(scale: float) -> str:

    mx, my = MARK_CENTER

    return f"translate(256 256) scale({scale}) translate({-mx} {-my})"





def tile_background(rounded: bool) -> str:

    rx = ' rx="116"' if rounded else ""

    border = (

        '<rect id="hopr-border" x="2" y="2" width="508" height="508" rx="114" fill="none" stroke="#b19dff" stroke-opacity=".18" stroke-width="4"/>'

        if rounded

        else ""

    )

    return (

        "<defs>"

        '<linearGradient id="hopr-bg" x1="0" y1="0" x2="512" y2="512" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#1a1238"/><stop offset="1" stop-color="#07060f"/></linearGradient>'

        '<radialGradient id="hopr-glow" cx="410" cy="90" r="360" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#7a5af8" stop-opacity=".42"/><stop offset="1" stop-color="#7a5af8" stop-opacity="0"/></radialGradient>'

        "</defs>"

        f'<rect width="512" height="512"{rx} fill="url(#hopr-bg)"/>'

        f'<rect width="512" height="512"{rx} fill="url(#hopr-glow)"/>'

        f"{border}"

    )





# "opr" drawn with the same stroke as the mark, so the lockup reads "hopr".

WORD_PATHS = (

    '<ellipse cx="584" cy="294" rx="100" ry="108"/>'

    '<path d="M784 196V500"/>'

    '<ellipse cx="884" cy="294" rx="100" ry="108"/>'

    '<path d="M1084 402V300C1084 226 1128 188 1198 192"/>'

)





def lockup(ink: str) -> str:

    return (

        f"{defs('dark' if ink != '#0e0b1f' else 'light')}"

        f"{mark_paths(ball_glow=False)}"

        f'<g fill="none" stroke="{ink}" stroke-width="{STROKE}" stroke-linecap="round" stroke-linejoin="round">{WORD_PATHS}</g>'

    )





# Favicons follow the OS theme: a light tile with deeper strokes in light mode,
# matching the in-app BrandLogo (src/components/BrandLogo.tsx).
LIGHT_SCHEME = (
    "<style>@media (prefers-color-scheme: light){"
    "#hopr-bg stop:nth-child(1){stop-color:#ffffff}#hopr-bg stop:nth-child(2){stop-color:#eee9ff}"
    "#hopr-glow stop{stop-color:#b7a3ff}#hopr-border{stroke:#6744ec}"
    "#hopr-stroke stop:nth-child(1){stop-color:#4325d6}#hopr-stroke stop:nth-child(2){stop-color:#6646f0}#hopr-stroke stop:nth-child(3){stop-color:#9a7dff}"
    "#hopr-ball stop:nth-child(1){stop-color:#c9fff0}#hopr-ball stop:nth-child(2){stop-color:#2fe0bb}#hopr-ball stop:nth-child(3){stop-color:#0c9f80}"
    "}</style>"
)


def main() -> None:

    x, y, w, h = MARK_BOX

    files = {

        "logo-mark.svg": svg(f"{x} {y} {w} {h}", defs() + mark_paths(ball_glow=False), w, h),

        "logo-icon.svg": svg("0 0 512 512", LIGHT_SCHEME + tile_background(True) + defs() + f'<g transform="{centered(0.94)}">{mark_paths()}</g>', 512, 512),

        # Circle-safe (Telegram crops avatars to a circle).

        "bot-avatar.svg": svg("0 0 512 512", tile_background(False) + defs() + f'<g transform="{centered(0.78)}">{mark_paths()}</g>', 512, 512),

        # Tiny sizes: heavier, larger, no halo so it stays legible at 16-32px.

        "favicon.svg": svg("0 0 512 512", LIGHT_SCHEME + tile_background(True) + defs() + f'<g transform="{centered(1.04)}">{mark_paths(ball_glow=False).replace(f'stroke-width="{STROKE}"', 'stroke-width="74"')}</g>', 512, 512),

        # Ink lockup for light backgrounds; the -light file is for dark backgrounds.

        "logo-full.svg": svg("96 66 1162 470", lockup("#0e0b1f"), 1162, 470, "hopr"),

        "logo-full-light.svg": svg("96 66 1162 470", lockup("#f3f0ff"), 1162, 470, "hopr"),

    }

    for name, content in files.items():

        (BRAND / name).write_text(content, encoding="utf-8")

        print("wrote", BRAND / name)





if __name__ == "__main__":

    main()

